### ISSUE TITLE
In Firefox is not working

### ISSUE THREAD

**Issue by BrutsSergio** [izolate/agegate#3]
https://izolate.github.io/agegate/   verified on your demo version
FF 49.0.1

**Comment by alexburgos** [comment]
Tested on FF 49.0.1, running into the same issue, console throwing a `e.srcElement is undefined` on click.

**Comment by samhh** [comment]
For some reason it appears that during build the latter half of this line: https://github.com/izolate/agegate/blob/master/src/index.js#L120

`let elements = e.target.elements`

Is being transpiled to `e.srcElement.elements`. `srcElement` is non-standard and is not supported in Firefox.

Curious...

**Comment by Jimmi08** [comment]
Confirmed.  Firefox 52.0.1 .

**Comment by ghost** [comment]
Idk if I understood the problem but its working here. Firefox 63. Maybe this is too old and just need to be closed?

**Comment by izolate** [comment]
Hi all, I'm sorry for the slow response. I've just released [v4.0.0](https://github.com/izolate/agegate/releases/tag/v4.0.0), which is a complete rewrite of this library, and therefore I'm closing this issue because it no longer applies to the current version.
