### ISSUE TITLE
Cookie path option

### ISSUE THREAD

**Issue by kthalmann** [izolate/agegate#5]
Option name for cookie path doesn't match the other cookie option names. 
Also the docs doesn't mention the option to set cookie path yet.

**Comment by izolate** [comment]
Hi @kthalmann - I'm sorry for the slow response. I've just released [v4.0.0](https://github.com/izolate/agegate/releases/tag/v4.0.0), which is a complete rewrite of this library, and therefore I'm closing this issue because it no longer applies to the current version.
