### ISSUE TITLE
Bug: Leaving Year field empty returns old_enough TRUE

### ISSUE THREAD

**Issue by rawrndres** [izolate/agegate#8]
Behaves different depending on browser, but Chrome allows access when leaving year field empty

**Comment by izolate** [comment]
Hi, thanks for filing this bug and I'm sorry for the slow response. I've just released [v4.0.0](https://github.com/izolate/agegate/releases/tag/v4.0.0), which is a complete rewrite of this library, and therefore I'm closing this issue because it no longer applies to the current version.
